n = input('digite Um número ou uma frase:')
print(type(n))
print('────────────────────────────────────────')
# (Lê letras Maiúscula ( M,D,L,A))
print('é so letra maiúscula?', n.isupper())
print('────────────────────────────────────────')
# (visualiza Letras e números juntos!)
print('é só número e letra juntos?', n.isalnum())
print('────────────────────────────────────────')
# (Só Funciona com Letras!)
print('é so letra?', n.isalpha())
print('────────────────────────────────────────')
# (só Funciona com Números!)
print('é so numero?', n.isnumeric())
print('────────────────────────────────────────')
# (lê números e simbolos ( 33/&$ ))
print('numero e simbols?', n.isascii())
print('────────────────────────────────────────')
# (Para funcionar só pode colocar espaço!)
print('é só espaço?', n.isspace())
print('────────────────────────────────────────')
# (Para funcionar o istitle não pode colocar espaço!)
print('Começou e terminou com letra maiúscula e minúscula?', n.istitle())
print('────────────────────────────────────────')